# Generated by Django 5.2.4 on 2025-08-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pushed', 'Pushed'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
